// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyVersionAttribute("1.0.1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1.0")>]
[<assembly: AssemblyTitleAttribute("Hello.World")>]
[<assembly: AssemblyDescriptionAttribute("Silly Test Package")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyVersion = "1.0.1.0"
    let [<Literal>] AssemblyFileVersion = "1.0.1.0"
    let [<Literal>] AssemblyTitle = "Hello.World"
    let [<Literal>] AssemblyDescription = "Silly Test Package"
